AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 18

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false