# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

development:
  secret_key_base: <%= Settings.auth.secret_key_base %>

test:
  secret_key_base: 383a238ab50a05f1bdb081a48551a1a3374b98db13db8fa20b181314d6d33713896d8147d7184224c135c1e7c06ad8ae6baa7dfd7d33e2a5ff787d442584137d

production:
  secret_key_base: <%= Settings.auth.secret_key_base %>
